### ISSUE TITLE
Title Bar: shouldn't be pure white

### ISSUE THREAD

**Issue by stormpython** [nteract/archived-desktop-app#4151]
**Application or Package Used**
nteract on web

**Describe the bug**
The title bar shouldn't be pure white. This is a regression from the typescript and styled components migration.

**To Reproduce**

1. Open up nteract

**Expected behavior**
Header style should be

```css
header.jsx-3942920302 {
    background-color: hsl(0, 0%, 94%));
    box-sizing: border-box;
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3149785/52009536-0f28e000-2488-11e9-9dc6-72074dc03fe1.png)
