### ISSUE TITLE
Add styling to blockquotes in markdown cells

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#810]
There's currently no styling to blockquotes, which makes it hard to tell if it's a paragraph vs. a quote.

![screen shot 2016-09-20 at 3 26 28 pm](https://cloud.githubusercontent.com/assets/836375/18691102/9fe8748c-7f46-11e6-867e-3c6615fee716.png)

Tempted to make an overly styled version:

![screen shot 2016-09-20 at 3 24 43 pm](https://cloud.githubusercontent.com/assets/836375/18691062/6235cb80-7f46-11e6-881d-6bbe593bccf6.png)

CSS:

``` css

blockquote{
  padding: .75em .5em .75em 1em;
  background: white;
  border-left: 0.5em solid #DDD;
}

blockquote::before {
  display: block;
  height: 0;
  content: "“";
  margin-left: -.95em;
  font: italic 400%/1 Open Serif,Georgia,"Times New Roman", serif;
  color: #999;
}

/* for nested paragraphs in block quotes */
blockquote p {
  display: inline;
}
```
